# Site settings.
title: Pixelite
email: admin@pixelite.co.nz
description: "A technology blog or rant area depending on the topic"
baseurl: ""
url: "http://www.pixelite.co.nz"
twitter_username: pixelite_
github_username:  pixelite-co-nz
facebook_username:

# Build settings.
markdown: kramdown
permalink: /article/:title
paginate: 21
exclude: ["node_modules"]
highlighter: pygments

# Thumbnail settings.
mini_magick:
  thumbnail:
    source: "img"
    destination: "img/thumbnail"
    resize: "800x520"

authors:
  Sean Hamlin:
    display_name: Sean Hamlin
    gravatar: b20e45d7e37337537d46738f60fbe888
    email: iwiifm@gmail.com
    web: http://www.pixelite.co.nz/authors/sean-hamlin/
    twitter: wiifm
    github: seanhamlin
    drupalorg: wiifm
    linkedin: shamlin
    blurb: "Technical Account Manager for Acquia working out of Wellington, New&nbsp;Zealand. Passionate about making awesome solutions to help solve complex business problems with Drupal integration and customisation. Working to bring open source to the world."
  Craig Pearson:
    display_name: Craig Pearson
    gravatar:
    email: thepearson@gmail.com
    web: http://www.pixelite.co.nz/authors/craig-pearson/
    twitter: thepearson
    github: thepearson
    linkedin:
    blurb:
  Gold:
    display_name: Gold
    gravatar:
    email: gold@freelancers.net.nz
    web: http://www.pixelite.co.nz/authors/gold/
    twitter: unifex
    github: Unifex
    drupalorg: gold
    linkedin:
    blurb:
  Josh Waihi:
    display_name: Josh Waihi
    gravatar:
    email: josh@joshwaihi.com
    web: http://www.joshwaihi.com/
    twitter: joshwaihi
    github: fiasco
    drupalorg: josh-waihi
    linkedin:
    blurb:
  Adam Bramley:
    display_name: Adam Bramley
    gravatar:
    email: eskimobob11@gmail.com
    web: http://www.pixelite.co.nz/authors/adam-bramley/
    twitter: theacbramley
    github: acbramley
    drupalorg: acbramley
    linkedin: acbramley
    blurb:
